/**
 * Follow-Up Task Service (Feature 5)
 *
 * Auto-generated by clinical events; doctors complete them and earn XP.
 *
 * Schema/codebase gotchas applied:
 *   • ESM modules — no `require`, use dynamic `import()` if needed.
 *   • notificationService.createNotification(...) — NOT `.create(...)`.
 *   • Notification has no `link` column → deep-link goes inside `data` JSON.
 *   • emitToUser(userId, event, payload) — no getSocketIO helper exists.
 *   • ClinicianXPService.awardXP(userId, action, xpAmount, sourceId, metadata)
 *     — positional args, NOT an options object.
 *   • Doctor.id ≠ User.id — Doctor.userId resolves to the User row.
 *   • Patient.fullName + user.email (User has no `name` column).
 *   • TaskPriority enum is shared (HIGH | MEDIUM | LOW).
 *   • FollowUpTaskStatus is the *new* enum — coexists with the unrelated
 *     FollowUpStatus enum used by AppointmentFollowUp.
 */

import prisma from '../lib/prisma.js';
import logger from '../lib/logger.js';
import { notificationService } from './notification.service.js';
import { emitToUser } from '../websocket/index.js';
import { ClinicianXPService } from './clinicianXP.service.js';

// ── XP per priority (matches the spec) ───────────────────────────────────────
const XP_BY_PRIORITY = { HIGH: 15, MEDIUM: 10, LOW: 5 };

// In-memory cache: Doctor.id → User.id. Cheap and safe — these never change.
const doctorUserIdCache = new Map();

/**
 * Look up the User.id for a given Doctor.id. Cached for the process lifetime
 * because the Doctor.userId mapping is immutable once provisioned.
 */
export async function getDoctorUserId(doctorId) {
    if (!doctorId) return null;
    if (doctorUserIdCache.has(doctorId)) return doctorUserIdCache.get(doctorId);
    const doctor = await prisma.doctor.findUnique({
        where: { id: doctorId },
        select: { userId: true },
    });
    const userId = doctor?.userId || null;
    if (userId) doctorUserIdCache.set(doctorId, userId);
    return userId;
}

/**
 * Resolve the Doctor.id assigned to a patient. Strategy (in order):
 *   1. PatientAssignment with type=PRIMARY + status=ACTIVE
 *   2. Most recent appointment.doctorId for the patient
 *   3. null (caller decides whether to skip)
 *
 * Used by all four auto-trigger hooks. Never throws.
 */
export async function resolveAssignedDoctorId(patientId) {
    if (!patientId) return null;
    try {
        const assignment = await prisma.patientAssignment.findFirst({
            where: { patientId, status: 'ACTIVE', type: 'PRIMARY' },
            orderBy: { assignedAt: 'desc' },
            select: { doctorId: true },
        });
        if (assignment?.doctorId) return assignment.doctorId;

        const lastAppt = await prisma.appointment.findFirst({
            where: { patientId, doctorId: { not: null } },
            orderBy: { date: 'desc' },
            select: { doctorId: true },
        });
        return lastAppt?.doctorId || null;
    } catch (err) {
        logger.warn('[FollowUpTask] resolveAssignedDoctorId failed', { patientId, err: err.message });
        return null;
    }
}

/**
 * Create a follow-up task. Idempotent on (triggerType, triggerRef) — when a
 * PENDING/IN_PROGRESS task already exists for the same source record, the
 * existing row is returned instead of creating a duplicate.
 *
 * Side effects (best-effort, never block):
 *   - In-app notification to the doctor.
 *   - Socket.IO `follow_up_task_created` event to the doctor's user room.
 */
export async function createFollowUpTask({
    doctorId,
    patientId,
    title,
    description,
    priority,
    dueDays,
    triggerType,
    triggerRef,
}) {
    if (!doctorId || !patientId || !title || !triggerType) {
        const e = new Error('doctorId, patientId, title, and triggerType are required');
        e.status = 400;
        throw e;
    }

    // Idempotency.
    if (triggerRef) {
        const existing = await prisma.followUpTask.findFirst({
            where: {
                triggerType,
                triggerRef,
                status: { in: ['PENDING', 'IN_PROGRESS'] },
            },
        });
        if (existing) {
            return { task: existing, alreadyExisted: true };
        }
    }

    const dueDate = new Date();
    dueDate.setDate(dueDate.getDate() + (Number.isFinite(dueDays) ? dueDays : 1));

    const finalPriority = ['HIGH', 'MEDIUM', 'LOW'].includes(priority) ? priority : 'MEDIUM';

    const task = await prisma.followUpTask.create({
        data: {
            doctorId,
            patientId,
            title,
            description: description || null,
            priority:    finalPriority,
            status:      'PENDING',
            dueDate,
            triggerType,
            triggerRef:  triggerRef || null,
            xpAwarded:   false,
        },
    });

    // Notify the doctor — fire-and-forget; failures only land in the log.
    const doctorUserId = await getDoctorUserId(doctorId);
    if (doctorUserId) {
        try {
            await notificationService.createNotification({
                userId:    doctorUserId,
                type:      'FOLLOW_UP_TASK_CREATED',
                title:     `New Follow-Up Task — ${finalPriority} Priority`,
                message:   title,
                priority:  finalPriority === 'HIGH' ? 'HIGH' : finalPriority === 'MEDIUM' ? 'MEDIUM' : 'INFO',
                relatedId: task.id,
                data: {
                    link: '/doctor?tab=follow-up-tasks',
                    taskId: task.id,
                    triggerType,
                    priority: finalPriority,
                },
            });
        } catch (err) {
            logger.warn('[FollowUpTask] notification failed', { taskId: task.id, err: err.message });
        }
        try {
            emitToUser(doctorUserId, 'follow_up_task_created', {
                taskId: task.id,
                title: task.title,
                priority: task.priority,
                dueDate: task.dueDate,
                triggerType: task.triggerType,
            });
        } catch (err) {
            logger.warn('[FollowUpTask] socket emit failed', { taskId: task.id, err: err.message });
        }
    }

    return { task, alreadyExisted: false };
}

/**
 * Mark a follow-up task COMPLETED, award XP via the existing ClinicianXP
 * pipeline, and write an audit log entry.
 *
 * XP failure does NOT block completion — `xpAwarded` stays false on the row
 * and the next call (re-attempt) can retry. Returns `{ task, xpAmount, xpAwarded }`.
 *
 * @param {string} taskId
 * @param {string} doctorUserId  — User.id of the calling doctor (for XP + audit)
 * @param {string|null} completionNote
 */
export async function completeFollowUpTask(taskId, doctorUserId, completionNote) {
    const task = await prisma.followUpTask.findUnique({
        where: { id: taskId },
        include: { doctor: { select: { userId: true } } },
    });
    if (!task) {
        const e = new Error('Task not found');
        e.status = 404;
        throw e;
    }
    if (task.status === 'COMPLETED') {
        const e = new Error('Task already completed');
        e.status = 409;
        throw e;
    }

    const xpAmount = XP_BY_PRIORITY[task.priority] ?? 5;

    const updated = await prisma.followUpTask.update({
        where: { id: taskId },
        data: {
            status: 'COMPLETED',
            completedAt: new Date(),
            completionNote: completionNote || null,
            // xpAwarded is flipped below after a successful XP grant.
        },
    });

    let xpAwarded = false;
    try {
        // ClinicianXPService is a no-op for ADMIN_DOCTOR (returns null) — that's
        // fine, the task still completes and the audit log records it.
        const xpResult = await ClinicianXPService.awardXP(
            doctorUserId,
            'FOLLOW_UP_TASK_COMPLETED',
            xpAmount,
            taskId,
            { taskTitle: task.title, priority: task.priority, triggerType: task.triggerType },
        );
        if (xpResult) {
            await prisma.followUpTask.update({
                where: { id: taskId },
                data: { xpAwarded: true },
            });
            xpAwarded = true;
        }
    } catch (xpErr) {
        // Spec rule: XP failure must NOT block task completion.
        logger.warn('[FollowUpTask] XP award failed', { taskId, err: xpErr.message });
    }

    try {
        await prisma.auditLog.create({
            data: {
                userId:     doctorUserId || null,
                action:     'FOLLOW_UP_TASK_COMPLETED',
                entityType: 'FollowUpTask',
                entityId:   taskId,
                newData: {
                    completionNote: completionNote || null,
                    xpAmount,
                    xpAwarded,
                    priority: task.priority,
                    triggerType: task.triggerType,
                },
            },
        });
    } catch (err) {
        logger.warn('[FollowUpTask] audit log failed', { taskId, err: err.message });
    }

    return { task: { ...updated, xpAwarded }, xpAmount, xpAwarded };
}

/** Sort order helper — HIGH → MEDIUM → LOW, then by dueDate ascending. */
const PRIORITY_ORDER = { HIGH: 0, MEDIUM: 1, LOW: 2 };

/**
 * List a doctor's follow-up tasks. Filters: status, priority, date.
 * Returns the rows with patient names already resolved (Doctor.fullName +
 * user.email fallback).
 */
export async function getDoctorTasks(doctorId, { status, priority, date } = {}) {
    if (!doctorId) return [];
    const where = { doctorId };

    if (status)   where.status   = status;
    if (priority) where.priority = priority;

    if (date === 'today') {
        const start = new Date(); start.setHours(0, 0, 0, 0);
        const end   = new Date(); end.setHours(23, 59, 59, 999);
        where.dueDate = { gte: start, lte: end };
    } else if (date === 'overdue') {
        where.dueDate = { lt: new Date() };
        // Overdue only makes sense for not-yet-done tasks.
        where.status  = { in: ['PENDING', 'IN_PROGRESS'] };
    }

    const tasks = await prisma.followUpTask.findMany({
        where,
        include: {
            patient: {
                select: {
                    id: true,
                    fullName: true,
                    profilePhoto: true,
                    user: { select: { email: true } },
                },
            },
        },
    });

    // Sort in JS — HIGH first, then dueDate asc. Prisma alphabetical enum
    // ordering would put HIGH before LOW but MEDIUM before HIGH.
    tasks.sort((a, b) => {
        const pd = (PRIORITY_ORDER[a.priority] ?? 9) - (PRIORITY_ORDER[b.priority] ?? 9);
        if (pd !== 0) return pd;
        return new Date(a.dueDate) - new Date(b.dueDate);
    });

    return tasks.map((t) => ({
        id:             t.id,
        title:          t.title,
        description:    t.description,
        priority:       t.priority,
        status:         t.status,
        dueDate:        t.dueDate,
        triggerType:    t.triggerType,
        triggerRef:     t.triggerRef,
        completedAt:    t.completedAt,
        completionNote: t.completionNote,
        xpAwarded:      t.xpAwarded,
        createdAt:      t.createdAt,
        patientId:      t.patientId,
        patientName:    t.patient?.fullName || t.patient?.user?.email || 'Unknown',
        patientAvatar:  t.patient?.profilePhoto || null,
    }));
}

/**
 * Counts shown on the morning panel header (pending / overdue / highPriority).
 * One round-trip — three concurrent counts.
 */
export async function getDoctorTaskSummary(doctorId) {
    if (!doctorId) return { pending: 0, overdue: 0, highPriority: 0 };
    const now = new Date();
    const [pending, overdue, highPriority] = await Promise.all([
        prisma.followUpTask.count({
            where: { doctorId, status: 'PENDING' },
        }),
        prisma.followUpTask.count({
            where: {
                doctorId,
                status:  { in: ['PENDING', 'IN_PROGRESS'] },
                dueDate: { lt: now },
            },
        }),
        prisma.followUpTask.count({
            where: { doctorId, status: 'PENDING', priority: 'HIGH' },
        }),
    ]);
    return { pending, overdue, highPriority };
}

/**
 * Update a task's status (used by the "Mark In Progress" / "Dismiss" actions).
 * Verifies caller ownership at the route layer; this helper only does the
 * write.
 */
export async function updateFollowUpTaskStatus(taskId, nextStatus) {
    const allowed = ['PENDING', 'IN_PROGRESS', 'DISMISSED'];
    if (!allowed.includes(nextStatus)) {
        const e = new Error(`Invalid status. Must be one of: ${allowed.join(', ')}`);
        e.status = 400;
        throw e;
    }
    return prisma.followUpTask.update({
        where: { id: taskId },
        data:  { status: nextStatus },
    });
}

// ═════════════════════════════════════════════════════════════════════════════
// AUTO-TRIGGERS — invoked fire-and-forget from clinical event hooks. Each one
// resolves the assigned doctor itself, never throws, and silently no-ops if a
// duplicate already exists (idempotency lives inside createFollowUpTask).
// ═════════════════════════════════════════════════════════════════════════════

/**
 * Trigger 1 — Triage submitted with swelling OR pain ≥ 7.
 *
 * Schema: TriageSession.painRegions Json? (NOT bodyRegions). Each region
 * stores `painCharacter`/`character` and `painIntensity`/`intensity` under
 * varying keys depending on which triage form version produced the row.
 */
export async function fireFollowUpFromTriage(triageSession) {
    if (!triageSession?.id || !triageSession?.patientId) return;
    try {
        const doctorId = await resolveAssignedDoctorId(triageSession.patientId);
        if (!doctorId) {
            logger.info('[FollowUpTask] triage trigger skipped — no assigned doctor', {
                patientId: triageSession.patientId,
            });
            return;
        }

        // patient name for human-readable title.
        const patient = await prisma.patient.findUnique({
            where: { id: triageSession.patientId },
            select: { fullName: true, user: { select: { email: true } } },
        });
        const patientName = patient?.fullName || patient?.user?.email || 'Patient';

        // Inspect painRegions JSON for swelling and the highest intensity.
        const regions = Array.isArray(triageSession.painRegions) ? triageSession.painRegions : [];
        const charactersOf = (r) => {
            const raw = r?.painCharacter ?? r?.character ?? r?.characters ?? r?.type ?? '';
            const arr = Array.isArray(raw) ? raw : [raw];
            return arr.map((s) => String(s || '').toLowerCase());
        };
        const hasSwelling = regions.some((r) => charactersOf(r).some((c) => c.includes('swell')));
        const intensityOf = (r) => {
            const v = r?.painIntensity ?? r?.intensity ?? r?.severity ?? r?.score;
            const n = typeof v === 'string' ? parseFloat(v) : v;
            return typeof n === 'number' && isFinite(n) ? n : 0;
        };
        const highestPain = regions.reduce((max, r) => Math.max(max, intensityOf(r)), 0);

        if (hasSwelling) {
            const swellingRegions = regions
                .filter((r) => charactersOf(r).some((c) => c.includes('swell')))
                .map((r) => r?.region || r?.bodyPart || r?.regionLabel || r?.name || 'unspecified region')
                .filter(Boolean)
                .join(', ');
            await createFollowUpTask({
                doctorId,
                patientId: triageSession.patientId,
                title: `Review swelling — ${patientName}`,
                description: `Patient reported swelling in triage${swellingRegions ? ` (${swellingRegions})` : ''}.`
                    + (triageSession.compositeScore != null ? ` Composite triage score: ${triageSession.compositeScore}.` : '')
                    + (triageSession.urgencyLevel ? ` Urgency: ${triageSession.urgencyLevel}.` : ''),
                priority: 'HIGH',
                dueDays: 5,
                triggerType: 'TRIAGE_SWELLING',
                triggerRef: triageSession.id,
            });
        } else if (highestPain >= 7) {
            await createFollowUpTask({
                doctorId,
                patientId: triageSession.patientId,
                title: `High pain triage — ${patientName} — pain ${highestPain}/10`,
                description: `Patient reported pain intensity ${highestPain}/10 in triage.`
                    + (triageSession.urgencyLevel ? ` Urgency: ${triageSession.urgencyLevel}.` : '')
                    + ' Review within 48 hours.',
                priority: 'HIGH',
                dueDays: 2,
                triggerType: 'TRIAGE_HIGH_PAIN',
                triggerRef: triageSession.id,
            });
        }
    } catch (err) {
        logger.warn('[FollowUpTask] triage trigger failed', { err: err.message, triageId: triageSession?.id });
    }
}

/**
 * Trigger 2 — Appointment marked COMPLETED and most-recent pain vital > 7.
 *
 * PatientVital.patientId references User.id (NOT Patient.id) per schema —
 * we translate via Patient.userId.
 */
export async function fireFollowUpFromAppointmentCompletion(appointmentId) {
    if (!appointmentId) return;
    try {
        const appointment = await prisma.appointment.findUnique({
            where: { id: appointmentId },
            include: {
                patient: {
                    select: {
                        id: true,
                        userId: true,
                        fullName: true,
                        user: { select: { email: true } },
                    },
                },
            },
        });
        if (!appointment?.doctorId || !appointment?.patientId) return;

        const vitalLookupId = appointment.patient?.userId || appointment.patientId;
        const latestPainVital = await prisma.patientVital.findFirst({
            where: { patientId: vitalLookupId, type: 'PAIN' },
            orderBy: { recordedAt: 'desc' },
        });
        const painScore = latestPainVital?.value;
        if (typeof painScore !== 'number' || painScore <= 7) return;

        const patientName = appointment.patient?.fullName || appointment.patient?.user?.email || 'Patient';
        await createFollowUpTask({
            doctorId:    appointment.doctorId,
            patientId:   appointment.patientId,
            title:       `High pain follow-up — ${patientName} — pain ${painScore}/10`,
            description: `Patient had pain score ${painScore}/10 at end of consultation on `
                + `${new Date().toLocaleDateString('en-IN')}. Review in 2 days.`,
            priority:    'HIGH',
            dueDays:     2,
            triggerType: 'CONSULTATION_HIGH_PAIN',
            triggerRef:  appointment.id,
        });
    } catch (err) {
        logger.warn('[FollowUpTask] appointment trigger failed', { err: err.message, appointmentId });
    }
}

/**
 * Trigger 4 — JourneyPhase flips to ACTIVE (the schema's equivalent of
 * "IN_PROGRESS"). Fired from JourneyService after activateNextPhase commits.
 *
 * journey.patientId / .doctorId both store User.id — translate to
 * Patient.id / Doctor.id before creating the task.
 */
export async function fireFollowUpFromPhaseActivation(journeyId, phase) {
    if (!journeyId || !phase?.id) return;
    try {
        const journey = await prisma.treatmentJourney.findUnique({
            where: { id: journeyId },
            select: { patientId: true, doctorId: true },
        });
        if (!journey?.patientId || !journey?.doctorId) return;

        const [patient, doctor] = await Promise.all([
            prisma.patient.findUnique({
                where: { userId: journey.patientId },
                select: { id: true, fullName: true, user: { select: { email: true } } },
            }),
            prisma.doctor.findUnique({
                where: { userId: journey.doctorId },
                select: { id: true },
            }),
        ]);
        if (!patient?.id || !doctor?.id) return;

        const patientName = patient.fullName || patient.user?.email || 'Patient';
        await createFollowUpTask({
            doctorId:    doctor.id,
            patientId:   patient.id,
            title:       `Check phase progress — ${patientName} — ${phase.name}`,
            description: `${phase.name} started today. Check task completion in 7 days and adjust if needed.`,
            priority:    'LOW',
            dueDays:     7,
            triggerType: 'PHASE_STARTED',
            triggerRef:  phase.id,
        });
    } catch (err) {
        logger.warn('[FollowUpTask] phase activation trigger failed', { err: err.message, phaseId: phase?.id });
    }
}

/**
 * Trigger 3 — Daily diet adherence sweep. Active diet prescriptions whose
 * adherence over the last 7 days is below 60% generate a MEDIUM-priority task
 * (idempotent on (DIET_ADHERENCE_LOW, prescriptionId) so the daily sweep is
 * safe to run repeatedly).
 *
 * Registered as a cron in scheduler.service.js — exported here so the
 * scheduler can import it and the test harness can call it directly.
 */
export async function runDietAdherenceCheck() {
    const sevenDaysAgo = new Date();
    sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);

    const activePrescriptions = await prisma.dietPrescription.findMany({
        where: { isActive: true },
        select: {
            id: true,
            patientId: true,
            patient: {
                select: {
                    id: true,
                    fullName: true,
                    user: { select: { email: true } },
                },
            },
        },
    });

    let created = 0;
    let skipped = 0;
    for (const prescription of activePrescriptions) {
        try {
            const logs = await prisma.dietAdherenceLog.findMany({
                where: {
                    dietPrescriptionId: prescription.id,
                    loggedAt: { gte: sevenDaysAgo },
                },
                select: { followed: true },
            });
            if (logs.length === 0) { skipped++; continue; }

            const followed = logs.filter((l) => l.followed).length;
            const adherencePercent = Math.round((followed / logs.length) * 100);
            if (adherencePercent >= 60) { skipped++; continue; }

            const doctorId = await resolveAssignedDoctorId(prescription.patientId);
            if (!doctorId) { skipped++; continue; }

            const patientName = prescription.patient?.fullName
                             || prescription.patient?.user?.email
                             || 'Patient';

            const result = await createFollowUpTask({
                doctorId,
                patientId: prescription.patientId,
                title: `Low diet adherence — ${patientName} — ${adherencePercent}%`,
                description: `${patientName} has followed only ${adherencePercent}% of their diet plan `
                    + `(${followed}/${logs.length} meals) over the last 7 days. Discuss barriers in next session.`,
                priority: 'MEDIUM',
                dueDays:  3,
                triggerType: 'DIET_ADHERENCE_LOW',
                triggerRef:  prescription.id,
            });
            if (result.alreadyExisted) skipped++; else created++;
        } catch (err) {
            logger.warn('[FollowUpTask] diet sweep — single prescription failed', {
                prescriptionId: prescription.id, err: err.message,
            });
        }
    }

    logger.info('[FollowUpTask] runDietAdherenceCheck done', {
        scanned: activePrescriptions.length, created, skipped,
    });
    return { scanned: activePrescriptions.length, created, skipped };
}

export default {
    XP_BY_PRIORITY,
    createFollowUpTask,
    completeFollowUpTask,
    getDoctorTasks,
    getDoctorTaskSummary,
    getDoctorUserId,
    resolveAssignedDoctorId,
    updateFollowUpTaskStatus,
    fireFollowUpFromTriage,
    fireFollowUpFromAppointmentCompletion,
    fireFollowUpFromPhaseActivation,
    runDietAdherenceCheck,
};
