// Monday Motivation Card service.
//
// Picks one personalized weekly tip based on the patient's prakriti
// (Vata / Pitta / Kapha — falls back to GENERAL if not onboarded) and
// the current Indian season (HEMANTA / SHISHIRA / VASANTA / GRISHMA /
// VARSHA / SHARAD). The day-of-year is used as a deterministic offset
// inside the chosen 30-tip cell so consecutive weeks produce different
// tips even when prakriti+season are stable.
//
// Card lifecycle:
//   1. Cron at 10:00 IST every Monday (handler in scheduledJobs.service.js)
//      calls generateDailyCardsForAllPatients() — creates one row per
//      active patient and ships the WhatsApp Monday Motivation message.
//   2. Patient opens dashboard → GET /api/motivation/today fetches this
//      week's card. If no row exists yet (cron hasn't fired, patient
//      onboarded mid-week), it lazily creates one inline. The lazy-create
//      path does NOT fire WhatsApp — Monday-cron is the only sender, so
//      patients never receive mid-week messages.
//   3. Patient taps "Got it" → POST /api/motivation/:id/read marks isRead
//      and awards +5 Zen Points (rate-limited 1/day).
//   4. Patient toggles save → POST /api/motivation/:id/save flips isSaved.
//   5. "My Tips" tab → GET /api/motivation/saved returns the saved list.

import prisma from '../lib/prisma.js';
import logger from '../lib/logger.js';
import {
  AYURVEDIC_TIPS,
  getCurrentSeason,
  getDayOfYear,
  getTipForPatient,
} from '../data/ayurvedicTips.js';
import { ZenPointsService } from './zenPoints.service.js';
import { WhatsAppService } from './whatsapp.service.js';
// F05 · Behavioural Nudge Engine — when the hospital has the
// BEHAVIOURAL_NUDGE_ENGINE feature flag enabled, the per-patient message body
// is generated by an LLM tailored to a patient profile + classified archetype
// instead of the static AYURVEDIC_TIPS lookup. The static path stays the
// default; flag-off hospitals see the existing Monday Motivation message
// byte-for-byte.
import { classifyPatient } from './nudge/profileClassifier.js';
import { generateNudgeMessage } from './nudge/messageGenerator.js';

// F05 helpers — batched LLM to dodge OpenAI rate limits.
const NUDGE_BATCH_SIZE = 10;
const NUDGE_BATCH_DELAY_MS = 500;
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

function startOfDay(d = new Date()) {
  const x = new Date(d);
  x.setHours(0, 0, 0, 0);
  return x;
}

function normalizePrakriti(raw) {
  if (!raw) return 'GENERAL';
  const upper = String(raw).toUpperCase();
  if (upper === 'VATA' || upper === 'PITTA' || upper === 'KAPHA') return upper;
  return 'GENERAL';
}

function extractPrakriti(patient) {
  // onboardingData is a free-form JSON column. Doctors / onboarding flow
  // historically wrote prakriti under different keys; check the common ones
  // before giving up to GENERAL.
  const data = patient?.onboardingData;
  if (!data || typeof data !== 'object') return 'GENERAL';
  return normalizePrakriti(
    data.prakriti ??
      data.dosha ??
      data.constitution ??
      data.bodyType ??
      data.body_type,
  );
}

// ── F05 · Per-hospital feature flag resolution ────────────────────────────
// Cached per cron run so we don't re-query HospitalFeatureFlag for every
// patient. Mirrors the registered/enabled three-state logic in
// utils/featureGate.js so unregistered keys fail OPEN (won't happen for
// BEHAVIOURAL_NUDGE_ENGINE — it's already in the FeatureRegistry seed —
// but keeps semantics consistent across the codebase).
function makeFeatureCache(featureKey) {
  const cache = new Map();
  return async (hospitalId) => {
    if (!hospitalId) return false;
    if (cache.has(hospitalId)) return cache.get(hospitalId);
    let enabled = false;
    try {
      const registry = await prisma.featureRegistry.findUnique({
        where: { key: featureKey },
        select: { isCore: true, defaultEnabled: true },
      });
      if (!registry) {
        // Unregistered — match featureGate.js fail-open behaviour.
        enabled = true;
      } else if (registry.isCore) {
        enabled = true;
      } else {
        const row = await prisma.hospitalFeatureFlag.findUnique({
          where: { hospitalId_featureKey: { hospitalId, featureKey } },
          select: { enabled: true },
        });
        enabled = row ? row.enabled : registry.defaultEnabled;
      }
    } catch (err) {
      logger.warn('[nudge] feature-flag lookup failed — defaulting OFF', {
        hospitalId, featureKey, err: err.message,
      });
      enabled = false;
    }
    cache.set(hospitalId, enabled);
    return enabled;
  };
}

// ── F05 · Per-patient profile snapshot for the nudge classifier ───────────
// Single function, deliberately wide try/catch — a missing constitution row
// or zero check-ins must not break the loop. Returns sensible zero-defaults
// so the classifier always lands at LOSS_AVERSE for fresh patients with no
// behavioural signal yet.
async function buildPatientProfile(patientId) {
  const since14 = new Date(Date.now() - 14 * 24 * 60 * 60 * 1000);
  const since7  = new Date(Date.now() -  7 * 24 * 60 * 60 * 1000);

  let prakriti = null;
  let streakDays = 0;
  let checkIns = [];

  try {
    const cp = await prisma.constitutionProfile.findUnique({
      where: { patientId }, select: { prakriti: true },
    });
    prakriti = cp?.prakriti ?? null;
  } catch (err) {
    logger.warn('[nudge] ConstitutionProfile lookup failed', { patientId, err: err.message });
  }

  try {
    const streak = await prisma.patientStreak.findUnique({
      where: { patientId }, select: { currentStreak: true },
    });
    streakDays = streak?.currentStreak ?? 0;
  } catch (err) {
    logger.warn('[nudge] PatientStreak lookup failed', { patientId, err: err.message });
  }

  try {
    checkIns = await prisma.dailyCheckIn.findMany({
      where: { patientId, createdAt: { gte: since14 } },
      select: { painLevel: true, sleepHours: true, createdAt: true },
      orderBy: { createdAt: 'desc' },
    });
  } catch (err) {
    logger.warn('[nudge] DailyCheckIn lookup failed', { patientId, err: err.message });
  }

  // checkInRate = unique check-in days (capped at 14) / 14. We dedupe per
  // calendar day so two check-ins in one day don't inflate the rate.
  const uniqueDays = new Set(
    checkIns.map((c) => new Date(c.createdAt).toISOString().slice(0, 10)),
  );
  const checkInRate = Math.min(uniqueDays.size, 14) / 14;

  // painTrend / sleepTrend = mean(last 7d) − mean(prior 7d).
  // Negative painTrend = pain is improving. Positive sleepTrend = more sleep.
  const last7  = checkIns.filter((c) => new Date(c.createdAt) >= since7);
  const prior7 = checkIns.filter((c) => new Date(c.createdAt) <  since7);
  const mean = (arr, key) =>
    arr.length === 0 ? 0 : arr.reduce((s, x) => s + (x[key] ?? 0), 0) / arr.length;
  const painTrend  = mean(last7, 'painLevel')  - mean(prior7, 'painLevel');
  const sleepTrend = mean(last7, 'sleepHours') - mean(prior7, 'sleepHours');

  const lastCheckInDaysAgo = checkIns.length === 0
    ? Number.POSITIVE_INFINITY
    : (Date.now() - new Date(checkIns[0].createdAt).getTime()) / (24 * 60 * 60 * 1000);

  return {
    prakriti,
    streakDays,
    checkInRate,
    painTrend,
    sleepTrend,
    lastCheckInDaysAgo,
  };
}

export class MotivationService {
  /**
   * Pick today's tip for a patient — pure function, no DB writes.
   * Returns { tip, prakriti, season }.
   */
  static pickTipForToday(patient, now = new Date()) {
    const prakriti = extractPrakriti(patient);
    const dayOfYear = getDayOfYear(now);
    return getTipForPatient(prakriti, dayOfYear);
  }

  /**
   * Get (or lazily create) this week's motivation card for a patient.
   * Lazy-create does NOT send WhatsApp — Monday-cron is the only sender,
   * so patients can't be spammed mid-week by opening the dashboard.
   */
  static async getTodayCard(patientId) {
    const today = startOfDay();
    const patient = await prisma.patient.findUnique({
      where: { id: patientId },
      select: { id: true, onboardingData: true },
    });
    if (!patient) {
      throw new Error('Patient not found');
    }

    const existing = await prisma.dailyMotivationCard.findUnique({
      where: { patientId_date: { patientId, date: today } },
    });
    if (existing) return existing;

    const { tip, prakriti, season } = this.pickTipForToday(patient);
    // Race-safe upsert. Two simultaneous dashboard loads can both miss the
    // findUnique and both try to create — the @@unique([patientId, date])
    // constraint plus upsert collapses them into one row.
    return prisma.dailyMotivationCard.upsert({
      where: { patientId_date: { patientId, date: today } },
      update: {},
      create: {
        patientId,
        tip,
        prakriti,
        season,
        date: today,
      },
    });
  }

  /**
   * Mark a card as read. Awards +5 Zen Points the first time only
   * (rate-limited via PATIENT_RATE_LIMITS.MOTIVATION_READ).
   * Returns { card, awarded } where awarded is the awardPoints result
   * (or null if rate-limited or already read).
   */
  static async markRead(patientId, cardId) {
    const card = await prisma.dailyMotivationCard.findFirst({
      where: { id: cardId, patientId },
    });
    if (!card) {
      throw new Error('Motivation card not found');
    }

    let awarded = null;
    let updatedCard = card;

    if (!card.isRead) {
      updatedCard = await prisma.dailyMotivationCard.update({
        where: { id: cardId },
        data: { isRead: true, readAt: new Date() },
      });
      try {
        awarded = await ZenPointsService.awardPoints(patientId, 'MOTIVATION_READ', cardId);
      } catch (err) {
        logger.warn('[MondayMotivation] award MOTIVATION_READ failed', { err: err.message, patientId, cardId });
      }
    }

    return { card: updatedCard, awarded };
  }

  /**
   * Toggle the save flag on a card. Saved tips appear in "My Tips" tab.
   */
  static async toggleSave(patientId, cardId) {
    const card = await prisma.dailyMotivationCard.findFirst({
      where: { id: cardId, patientId },
    });
    if (!card) {
      throw new Error('Motivation card not found');
    }
    const isSaved = !card.isSaved;
    return prisma.dailyMotivationCard.update({
      where: { id: cardId },
      data: {
        isSaved,
        savedAt: isSaved ? new Date() : null,
      },
    });
  }

  /**
   * Saved tips for the My Tips tab — newest savedAt first.
   */
  static async getSavedTips(patientId, { limit = 100 } = {}) {
    return prisma.dailyMotivationCard.findMany({
      where: { patientId, isSaved: true },
      orderBy: { savedAt: 'desc' },
      take: limit,
    });
  }

  /**
   * Cron entry point — runs at 10:00 IST every Monday. Generates this
   * week's card for every active patient (onboarding completed) and pushes
   * a Monday Motivation WhatsApp message. No Zen Points awarded here —
   * only on the patient's "Got it" tap.
   *
   * Idempotent via @@unique([patientId, date]): a same-day re-run upserts
   * to the same row. Cards already messaged this week have whatsappSentAt
   * stamped so the WhatsApp dispatch self-skips.
   */
  static async generateDailyCardsForAllPatients() {
    const today = startOfDay();
    const season = getCurrentSeason(today);
    const dayOfYear = getDayOfYear(today);

    const patients = await prisma.patient.findMany({
      where: { onboardingCompleted: true },
      select: {
        id: true,
        fullName: true,
        onboardingData: true,
        user: {
          select: {
            // F05 — needed to evaluate the BEHAVIOURAL_NUDGE_ENGINE flag
            // per-hospital. Patient itself has no hospitalId column, so the
            // hospital is reached via User.
            hospitalId: true,
            notificationPreference: {
              select: {
                whatsappEnabled: true,
                whatsappNumber: true,
              },
            },
          },
        },
      },
    });

    // F05 — single cache for BEHAVIOURAL_NUDGE_ENGINE evaluations across
    // this cron run. Each hospital is queried at most once per run.
    const isNudgeFeatureEnabled = makeFeatureCache('BEHAVIOURAL_NUDGE_ENGINE');

    let processed = 0;
    let whatsappSent = 0;
    let whatsappSkipped = 0;
    let whatsappFailed = 0;
    let nudgesGenerated = 0;

    for (let batchStart = 0; batchStart < patients.length; batchStart += NUDGE_BATCH_SIZE) {
     const batch = patients.slice(batchStart, batchStart + NUDGE_BATCH_SIZE);
     for (const patient of batch) {
      try {
        const resolvedPrakriti = extractPrakriti(patient);
        // Reuse the same pure helper so every patient's tip across the
        // platform stays in lock-step with the on-demand path.
        const cell = AYURVEDIC_TIPS[resolvedPrakriti]?.[season] ?? AYURVEDIC_TIPS.GENERAL;
        const tip = cell[dayOfYear % cell.length];

        const card = await prisma.dailyMotivationCard.upsert({
          where: { patientId_date: { patientId: patient.id, date: today } },
          update: {},
          create: {
            patientId: patient.id,
            tip,
            prakriti: resolvedPrakriti,
            season,
            date: today,
          },
        });
        processed += 1;

        // Skip WhatsApp if already sent this week (same-day cron re-run).
        if (card.whatsappSentAt) {
          whatsappSkipped += 1;
          continue;
        }

        // Get patient's next upcoming appointment.
        const nextAppointment = await prisma.appointment.findFirst({
          where: {
            patientId: patient.id,
            status: { in: ['CONFIRMED', 'ACCEPTED'] },
            date: { gt: new Date() },
          },
          include: {
            doctor: { select: { fullName: true } },
          },
          orderBy: { date: 'asc' },
        });

        // Format appointment text.
        let appointmentText = '';
        if (nextAppointment) {
          const apptDate = new Date(nextAppointment.date);
          const dayName = apptDate.toLocaleDateString('en-IN', { weekday: 'long' });
          const dateStr = apptDate.toLocaleDateString('en-IN', {
            day: 'numeric', month: 'short',
          });
          const timeStr = apptDate.toLocaleTimeString('en-IN', {
            hour: '2-digit', minute: '2-digit',
          });
          // User has no `name` column; doctor name lives on Doctor.fullName.
          const doctorName = nextAppointment.doctor?.fullName || 'your doctor';
          appointmentText = `\n📅 Next appointment: ${doctorName} — ${dayName}, ${dateStr} at ${timeStr}`;
        }

        // Get patient streak — PatientStreak.patientId is unique.
        let streakText = '';
        try {
          const streakRecord = await prisma.patientStreak.findUnique({
            where: { patientId: patient.id },
          });
          const streakCount = streakRecord?.currentStreak ?? 0;
          if (streakCount > 0) {
            streakText = `\n🔥 Current streak: ${streakCount} days`;
          }
        } catch (e) {
          // Streak lookup failed — skip silently.
        }

        // Send WhatsApp if patient has number and has it enabled.
        const pref = patient.user?.notificationPreference;
        const whatsappNumber = pref?.whatsappNumber;
        const whatsappEnabled = pref?.whatsappEnabled;

        if (whatsappNumber && whatsappEnabled) {
          try {
            const patientFirstName = patient.fullName?.split(' ')[0] || 'there';
            const doshaLabel = resolvedPrakriti !== 'GENERAL'
              ? `your ${resolvedPrakriti.charAt(0) + resolvedPrakriti.slice(1).toLowerCase()} constitution`
              : 'your wellness journey';

            // ── F05 · per-hospital nudge branch ─────────────────────────────
            // Flag ON → LLM-generated personalised nudge (replaces full body).
            // Flag OFF → existing Monday Motivation templated message
            //            (preserved byte-for-byte; flag-off hospitals see no change).
            const hospitalId = patient.user?.hospitalId;
            const nudgeOn = await isNudgeFeatureEnabled(hospitalId);

            let message;
            if (nudgeOn) {
              const profile = await buildPatientProfile(patient.id);
              const { archetype } = classifyPatient(profile);
              const nudgeText = await generateNudgeMessage({ ...profile, archetype });

              // Log the attempt BEFORE the WhatsApp send so failed sends are
              // still part of the engagement-feedback dataset. Wrapped — a
              // NudgeLog write failure must never block message delivery.
              try {
                await prisma.nudgeLog.create({
                  data: {
                    patientId: patient.id,
                    archetype,
                    messageText: nudgeText,
                  },
                });
              } catch (err) {
                logger.warn('[nudge] NudgeLog create failed — continuing with send', {
                  patientId: patient.id, err: err.message,
                });
              }

              message = nudgeText;
              nudgesGenerated += 1;
            } else {
              message = `🌿 *Monday Motivation from Al-Shifa*\n\nGood morning, ${patientFirstName}! A new week begins 🌱\n\n*This week's Ayurvedic focus for ${doshaLabel}:*\n\n"${tip}"\n\n_${season} season_${streakText}${appointmentText}\n\nHave a healthy week 💚\n— Al-Shifa Care Team`;
            }

            // WhatsAppService.sendText is positional (number, text) — see
            // services/whatsapp.service.js. Returns { status: 'SENT' | 'SKIPPED' | 'FAILED' }.
            const result = await WhatsAppService.sendText(whatsappNumber, message);
            if (result?.status && result.status !== 'SENT') {
              whatsappFailed += 1;
              console.error(`[MondayMotivation] WhatsApp non-SENT (${result.status}) for patient ${patient.id}`);
            } else {
              await prisma.dailyMotivationCard.update({
                where: { id: card.id },
                data: { whatsappSentAt: new Date() },
              });
              whatsappSent += 1;
              console.log(`[MondayMotivation] WhatsApp sent to ${patientFirstName}`);
            }
          } catch (err) {
            whatsappFailed += 1;
            console.error(`[MondayMotivation] WhatsApp failed for patient ${patient.id}:`, err.message);
            // Never throw — always continue to next patient.
          }
        } else {
          whatsappSkipped += 1;
          console.log(`[MondayMotivation] Skipped WhatsApp for patient ${patient.id} — no number or disabled`);
        }
      } catch (err) {
        logger.error('[MondayMotivation] generate card failed', {
          err: err.message,
          patientId: patient.id,
        });
      }
     }
     // F05 — short pause between batches to stay below OpenAI rate limits.
     // No-op on the last batch.
     if (batchStart + NUDGE_BATCH_SIZE < patients.length) {
       await sleep(NUDGE_BATCH_DELAY_MS);
     }
    }

    logger.info('[MondayMotivation] weekly generation complete', {
      total: patients.length,
      processed,
      whatsappSent,
      whatsappSkipped,
      whatsappFailed,
      nudgesGenerated,
      season,
    });

    return {
      total: patients.length,
      processed,
      whatsappSent,
      whatsappSkipped,
      whatsappFailed,
      nudgesGenerated,
      season,
    };
  }
}

export default MotivationService;
